### ISSUE TITLE
DevOps Position Interaction?

### ISSUE THREAD

**Issue by tone81** [NGPVAN/job-descriptions#5]
"...candidates will provide a seamless integration point for Development and Information Technology..."

I think that a DevOps person would also interact with Product because ultimately Product determines what and when features come out. Would this be a realistic ask of the DevOps person?

**Comment by itsdrewmiller** [comment]
I don't think we will block anyone from any kind of interactions that are mutually beneficial, but so far in practice product hasn't been super involved in working with Shaun.  It probably does make sense at some level in the interaction of architecture, devops, and requirements, though - what kind of scale of problem are we trying to solve?
